### ISSUE TITLE
Nightmode switch works, but the CSS is broken

### ISSUE THREAD

**Issue by jacks-old-git** [malsf21/robotics-club-website#7]
I formatted the CSS weird and I'm pretty sure I broke it. Could also be that there are two CSS files at work. If it's the latter, let me know and I can add a light mode.

Night Mode:
![screen shot 2016-01-15 at 2 15 28 pm](https://cloud.githubusercontent.com/assets/6750720/12362642/76bfd5a0-bb92-11e5-91cc-e0a84d6ec668.png)

Light Mode:
![screen shot 2016-01-15 at 2 15 19 pm](https://cloud.githubusercontent.com/assets/6750720/12362643/76c17e0a-bb92-11e5-81bd-26cd7daa7935.png)

**Comment by mattxwang** [comment]
Hm, I'm looking through the CSS and it seems like the main issue is margins are double-applied. Give just loading nightmode and not normal, it should work ~ fine.

**Comment by mattxwang** [comment]
Yep, so with further research I've found out the problem. Basically, we need to unload the "light mode" css file first, then load in the pure "dark mode" css file (in this case that's bootstrap-night-plain.css). My old PHP function does the actual idea properly, the implementation is just wrong. Please take a look at that!

**Comment by mattxwang** [comment]
I've fixed nightmode, it now works properly.
